import datetime

def object_hook(dct):
    if "$dt" in dct:
        return parse_iso_datetime(dct["$dt"])
    return dct

def default(obj):
    if isinstance(obj, datetime.datetime):
        return {"$dt": obj.isoformat()}
    else:
        raise TypeError("%r is not JSON serializable" % obj)

def parse_iso_datetime(str) :
    # parse a datetime generated by datetime.isoformat()
    try :
        return datetime.datetime.strptime(str, "%Y-%m-%dT%H:%M:%S.%f")
    except ValueError :
        return datetime.datetime.strptime(str, "%Y-%m-%dT%H:%M:%S")
